-- MuhasebeLab — initial schema
-- Run with `supabase db push` once project is initialized.

create extension if not exists "pgcrypto";

-- =====================================================================
-- KATALOG (statik referans verisi — RLS: public read, service-role write)
-- =====================================================================

create table hesap_plani (
  kod text primary key,
  ad text not null,
  sinif text not null check (sinif in ('1','2','3','4','5','6','7')),
  tur text not null check (tur in ('AKTİF','PASİF','GELİR','GİDER','MALİYET','KAPANIŞ')),
  sira int generated by default as identity
);

create table unites (
  id text primary key,
  ad text not null,
  aciklama text,
  thiings_icon text,
  sira int not null default 0,
  created_at timestamptz not null default now()
);

create type soru_durum as enum ('taslak','inceleme','onayli','arsiv');
create type zorluk as enum ('kolay','orta','zor');

create table sorular (
  id text primary key,
  unite_id text not null references unites(id) on delete restrict,
  baslik text not null,
  zorluk zorluk not null,
  senaryo text not null,
  ipucu text,
  aciklama text,
  durum soru_durum not null default 'taslak',
  kaynak text,                               -- 'manuel' | 'ai' | 'kullanici'
  yayinlanma_tarihi timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index sorular_unite_idx on sorular (unite_id);
create index sorular_durum_idx on sorular (durum) where durum = 'onayli';

create table cozumler (
  id uuid primary key default gen_random_uuid(),
  soru_id text not null references sorular(id) on delete cascade,
  sira int not null,
  kod text not null references hesap_plani(kod),
  borc numeric(14,2) not null default 0,
  alacak numeric(14,2) not null default 0,
  unique (soru_id, sira)
);

create index cozumler_soru_idx on cozumler (soru_id);

create table rozetler_katalog (
  id text primary key,
  ad text not null,
  aciklama text not null,
  icon text not null,
  sira int not null default 0
);

-- =====================================================================
-- KULLANICI (auth.users uzantısı)
-- =====================================================================

create table kullanicilar (
  id uuid primary key references auth.users(id) on delete cascade,
  kullanici_adi text not null default 'Öğrenci',
  email text,
  tema text not null default 'light' check (tema in ('light','dark')),
  premium_bitis timestamptz,                 -- null = ücretsiz
  gunluk_limit_reset timestamptz,            -- son sıfırlama (saat dilimi: Europe/Istanbul)
  gunluk_cozum_sayisi int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Yeni auth kaydında otomatik profil oluştur
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.kullanicilar (id, email)
  values (new.id, new.email);
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =====================================================================
-- KULLANICI VERİLERİ
-- =====================================================================

create table ilerleme (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references kullanicilar(id) on delete cascade,
  soru_id text not null references sorular(id) on delete cascade,
  dogru_mu bool not null,
  sure_saniye int,
  created_at timestamptz not null default now()
);

create index ilerleme_user_idx on ilerleme (user_id);
create index ilerleme_user_soru_idx on ilerleme (user_id, soru_id);

create table kazanilan_rozetler (
  user_id uuid not null references kullanicilar(id) on delete cascade,
  rozet_id text not null references rozetler_katalog(id) on delete cascade,
  kazanilan_tarih timestamptz not null default now(),
  primary key (user_id, rozet_id)
);

create table aktivite (
  user_id uuid not null references kullanicilar(id) on delete cascade,
  tarih date not null,
  cozulen_sayi int not null default 0,
  primary key (user_id, tarih)
);

-- =====================================================================
-- ÖDEMELER (İyzico)
-- =====================================================================

create type odeme_durum as enum ('beklemede','basarili','iptal','iade','hata');
create type odeme_donem as enum ('aylik','yillik');

create table odemeler (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references kullanicilar(id) on delete restrict,
  iyzico_ref text unique,
  tutar numeric(10,2) not null,
  para_birimi text not null default 'TRY',
  donem odeme_donem not null,
  durum odeme_durum not null default 'beklemede',
  basarili_tarih timestamptz,
  ham_yanit jsonb,                           -- iyzico tam yanıtı (debug)
  created_at timestamptz not null default now()
);

create index odemeler_user_idx on odemeler (user_id);

-- =====================================================================
-- HATA BİLDİRİMLERİ (kullanıcı katkısı)
-- =====================================================================

create table soru_hatalari (
  id uuid primary key default gen_random_uuid(),
  soru_id text not null references sorular(id) on delete cascade,
  user_id uuid references kullanicilar(id) on delete set null,
  aciklama text not null,
  durum text not null default 'acik' check (durum in ('acik','incelemede','duzeltildi','reddedildi')),
  created_at timestamptz not null default now()
);

create index soru_hatalari_durum_idx on soru_hatalari (durum) where durum = 'acik';

-- =====================================================================
-- updated_at otomatik tetikleyici
-- =====================================================================

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger sorular_updated_at before update on sorular
  for each row execute function set_updated_at();
create trigger kullanicilar_updated_at before update on kullanicilar
  for each row execute function set_updated_at();

-- =====================================================================
-- ROW LEVEL SECURITY
-- =====================================================================

alter table hesap_plani enable row level security;
alter table unites enable row level security;
alter table sorular enable row level security;
alter table cozumler enable row level security;
alter table rozetler_katalog enable row level security;
alter table kullanicilar enable row level security;
alter table ilerleme enable row level security;
alter table kazanilan_rozetler enable row level security;
alter table aktivite enable row level security;
alter table odemeler enable row level security;
alter table soru_hatalari enable row level security;

-- Katalog: herkes okur
create policy "katalog_public_read_hesap_plani"
  on hesap_plani for select using (true);
create policy "katalog_public_read_unites"
  on unites for select using (true);
create policy "katalog_public_read_rozetler"
  on rozetler_katalog for select using (true);

-- Sorular: yalnız onaylı olanlar herkese; admin (service_role) hepsini görür
create policy "sorular_public_read_onayli"
  on sorular for select using (durum = 'onayli');
create policy "cozumler_public_read_onayli"
  on cozumler for select using (
    exists (select 1 from sorular s where s.id = cozumler.soru_id and s.durum = 'onayli')
  );

-- Kullanıcı: sadece kendi profilini okur/günceller
create policy "kullanici_own_select" on kullanicilar
  for select using (auth.uid() = id);
create policy "kullanici_own_update" on kullanicilar
  for update using (auth.uid() = id);

-- İlerleme: sadece kendi kayıtları
create policy "ilerleme_own_all" on ilerleme
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "rozet_own_all" on kazanilan_rozetler
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "aktivite_own_all" on aktivite
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "odeme_own_select" on odemeler
  for select using (auth.uid() = user_id);
-- Ödeme insert/update yalnız Edge Function (service_role) üzerinden yapılır.

-- Soru hata bildirimi: oturum açmış herkes ekleyebilir, kendi bildirimini okur
create policy "hata_authenticated_insert" on soru_hatalari
  for insert with check (auth.uid() is not null);
create policy "hata_own_select" on soru_hatalari
  for select using (auth.uid() = user_id);
